mysql:
  host: 127.0.0.1
  port: 3306
  user: root
  password: root
  
slave:
  server_id: 1111
  excludes_fields:
    - passwd
    - password
  schemas:
    - test

es:
  host: 127.0.0.1
  port: 9200
  bulk_size: 3

log:
  run: logs/run.log
  
binlog: 
  mark: etc/mark.info

email:
  host: smtp.gmail.com
  port: 587
  from:
    user: nobody@gmail.com
    passwd: pass
  to:
    - 421939022@qq.com
